-- default password = test
INSERT INTO FAMILY (ID, USERNAME, PASSWORD, NAME) VALUES (0, 'test', '$2a$11$wvfQIFmdNfsY2h7T0ef9NOp4rD0EXOOC12MK5DlRwiePLtyWMs1ZS', 'Teszt');

INSERT INTO TODO (ID, VERSION, FAMILY_ID, TASK, OWNER, STATUS) VALUES (200, 1, 0, 'Teszt feladat', 'Pisti', 0);
INSERT INTO TODO (ID, VERSION, FAMILY_ID, TASK, OWNER, STATUS) VALUES (600, 1, 0, 'Teszt feladat', 'Pisti', 0);
INSERT INTO TODO (ID, VERSION, FAMILY_ID, TASK, OWNER, STATUS) VALUES (900, 1, 0, 'Teszt feladat', 'Pisti', 0);
INSERT INTO TODO (ID, VERSION, FAMILY_ID, TASK, OWNER, STATUS) VALUES (300, 1, 0, 'Teszt feladat', 'Pisti', 0);
INSERT INTO TODO (ID, VERSION, FAMILY_ID, TASK, OWNER, STATUS) VALUES (400, 1, 0, 'Teszt feladat', 'Pisti', 0);
INSERT INTO TODO (ID, VERSION, FAMILY_ID, TASK, OWNER, STATUS) VALUES (500, 1, 0, 'Teszt feladat', 'Pisti', 0);